[theme]
primaryColor = "#4CAF50"             # Buttons, highlights, links
backgroundColor = "#f5f5f5"          # Main page background (pale grey)
secondaryBackgroundColor = "#e0e0e0" # Sidebar background (lighter grey)
textColor = "#000000"                # Black text everywhere (including titles and input text)
font = "sans serif"